name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
    - run: rustup update stable
    - run: rustup target add thumbv6m-none-eabi
    - uses: actions/checkout@v2
    - run: cargo test
    - name: Build no_std
      run: cargo build --target thumbv6m-none-eabi --no-default-features --features "variable-fonts opentype-layout glyph-names"

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
