name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
    - run: rustup update stable
    - run: rustup target add thumbv6m-none-eabi
    - uses: actions/checkout@v4
    - run: cargo test
    - name: Build no_std
      run: cargo build --target thumbv6m-none-eabi --no-default-features --features "no-std-float variable-fonts opentype-layout glyph-names"

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check
